from tkinter import *
from tkinter import ttk
from ApiRequests import APIRequests
DGB = APIRequests(input("Hotspot Address: "))
DGB.GetHotspotInfo()
DGB.GetHotspotActivity()
def MainLoop():
    root = Tk()
    root.geometry("400x600")
    root.title(DGB.rJson1['name'])
    HotspotFrame = Frame(root)
    HotspotFrame.grid(column=0, row=0)
    Button1 = Button(HotspotFrame, text="Refresh")
    Button1.bind("<Button-1>", DGB.GetHotspotInfo)
    Button1.grid(column=2, row=5)
    online = StringVar()
    height = StringVar()
    dbi = StringVar()
    online.set(DGB.rJson1['status']['online'])
    height.set(DGB.rJson1['status']['height'])
    dbi.set(f"{int(DGB.rJson1['gain'])/10}")
    hLabel1 = Label(HotspotFrame, text="Online Status:")
    hLabel2 = Label(HotspotFrame, textvariable=online)
    hLabel3 = Label(HotspotFrame, text="Block Height:")
    hLabel4 = Label(HotspotFrame, textvariable=height)
    hLabel5 = Label(HotspotFrame, text="Dbi:")
    hLabel6 = Label(HotspotFrame, textvariable=dbi)
    hLabel7 = Label(HotspotFrame, text="Hotspot Info", anchor=CENTER)
    hLabel1.grid(column=1,row=1)
    hLabel2.grid(column=2,row=1)
    hLabel3.grid(column=1,row=2)
    hLabel4.grid(column=2,row=2)
    hLabel5.grid(column=1,row=3)
    hLabel6.grid(column=2,row=3)
    hLabel7.grid(column=1,columnspan=2, row=0)
    root.mainloop()
MainLoop()
